// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeAPI.Data;

#nullable disable

namespace RecipeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531022306_AddSeedIngredients")]
    partial class AddSeedIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Morning meals",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Midday meals",
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Evening meals",
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sweet treats",
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Light bites",
                            Name = "Snack"
                        });
                });

            modelBuilder.Entity("RecipeAPI.Models.FavoriteRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteRecipes");
                });

            modelBuilder.Entity("RecipeAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "2",
                            Name = "Flour",
                            RecipeId = 1,
                            Unit = "cups"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "2",
                            Name = "Eggs",
                            RecipeId = 1,
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "1.5",
                            Name = "Milk",
                            RecipeId = 1,
                            Unit = "cups"
                        },
                        new
                        {
                            Id = 4,
                            Amount = "2",
                            Name = "Butter",
                            RecipeId = 1,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 5,
                            Amount = "400",
                            Name = "Spaghetti",
                            RecipeId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 6,
                            Amount = "300",
                            Name = "Ground beef",
                            RecipeId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 7,
                            Amount = "400",
                            Name = "Tomato sauce",
                            RecipeId = 2,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 8,
                            Amount = "1",
                            Name = "Onion",
                            RecipeId = 2,
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = 9,
                            Amount = "1",
                            Name = "Romaine lettuce",
                            RecipeId = 3,
                            Unit = "head"
                        },
                        new
                        {
                            Id = 10,
                            Amount = "4",
                            Name = "Caesar dressing",
                            RecipeId = 3,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 11,
                            Amount = "50",
                            Name = "Parmesan",
                            RecipeId = 3,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 12,
                            Amount = "1",
                            Name = "Croutons",
                            RecipeId = 3,
                            Unit = "cup"
                        },
                        new
                        {
                            Id = 13,
                            Amount = "200",
                            Name = "Dark chocolate",
                            RecipeId = 4,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 14,
                            Amount = "100",
                            Name = "Butter",
                            RecipeId = 4,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 15,
                            Amount = "200",
                            Name = "Sugar",
                            RecipeId = 4,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 16,
                            Amount = "100",
                            Name = "Flour",
                            RecipeId = 4,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 17,
                            Amount = "2",
                            Name = "Bread",
                            RecipeId = 5,
                            Unit = "slices"
                        },
                        new
                        {
                            Id = 18,
                            Amount = "1",
                            Name = "Avocado",
                            RecipeId = 5,
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = 19,
                            Amount = "1",
                            Name = "Lemon juice",
                            RecipeId = 5,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 20,
                            Amount = "1",
                            Name = "Salt",
                            RecipeId = 5,
                            Unit = "pinch"
                        });
                });

            modelBuilder.Entity("RecipeAPI.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookTimeMinutes = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fluffy and delicious pancakes perfect for breakfast.",
                            Instructions = "Mix flour, eggs, milk and butter. Cook on a hot pan until golden.",
                            PrepTimeMinutes = 10,
                            Servings = 4,
                            Title = "Classic Pancakes",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CookTimeMinutes = 30,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic Italian pasta dish with rich meat sauce.",
                            Instructions = "Brown the meat, add tomatoes and simmer. Cook pasta and combine.",
                            PrepTimeMinutes = 15,
                            Servings = 4,
                            Title = "Spaghetti Bolognese",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CookTimeMinutes = 0,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh romaine lettuce with creamy Caesar dressing.",
                            Instructions = "Chop lettuce, add croutons, parmesan and Caesar dressing. Toss well.",
                            PrepTimeMinutes = 10,
                            Servings = 2,
                            Title = "Caesar Salad",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CookTimeMinutes = 25,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich and fudgy chocolate brownies everyone will love.",
                            Instructions = "Melt chocolate and butter. Mix with eggs and flour. Bake at 180C for 25 minutes.",
                            PrepTimeMinutes = 15,
                            Servings = 8,
                            Title = "Chocolate Brownies",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CookTimeMinutes = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple and healthy avocado toast for a quick snack.",
                            Instructions = "Toast bread, mash avocado with lemon and salt. Spread on toast.",
                            PrepTimeMinutes = 5,
                            Servings = 1,
                            Title = "Avocado Toast",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RecipeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@recipe.com",
                            PasswordHash = "$2a$11$1dINb80632tjwWtpES4SxuaDzUUI3oR5aTVZf4vxB9WDZPyYxtXiu",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RecipeAPI.Models.FavoriteRecipe", b =>
                {
                    b.HasOne("RecipeAPI.Models.Recipe", "Recipe")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeAPI.Models.User", "User")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeAPI.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeAPI.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeAPI.Models.Recipe", b =>
                {
                    b.HasOne("RecipeAPI.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeAPI.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeAPI.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeAPI.Models.Recipe", b =>
                {
                    b.Navigation("FavoriteRecipes");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RecipeAPI.Models.User", b =>
                {
                    b.Navigation("FavoriteRecipes");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
